
version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: oliviertech/nestapp:1.0.0
    build: .
    ports:
      - 3000:5000
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=nestappdatabase 
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=5432
      - SECRET=${SECRET}
    depends_on:
      - dev-db
  dev-db:
    container_name: nestappdatabase
    image: postgres:13
    environment: 
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    # networks:
    #   - nesttesting
    volumes:
      - bookmarks:/var/lib/postgresql/data
volumes:
  bookmarks: {}

#   test-db:
#     image: postgres:13
#     environment: 
#       - POSTGRES_USER=${POSTGRES_TEST_USERNAME}
#       - POSTGRES_PASSWORD=${POSTGRES_TEST_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_TEST_DATABASE}
#     ports:
#       - ${POSTGRES_TEST_PORT}:5432
#     networks:
#       - nesttesting
# networks:
#   nesttesting: